// adblocker.js
(function () {
    'use strict';

    // List of ad-related selectors
    const adSelectors = [
        'iframe[src*="ads"]',
        'div[class*="ad"]',
        'img[src*="ad"]',
        'script[src*="ads"]',
        'ins.adsbygoogle',
        'div.ad-banner',
        'div.ad-container',
        'div.ad-wrapper',
        'div.ad-unit',
        'div.ad-placeholder',
        'div.ad-slot',
        'div.ad-frame',
        'div.ad-popup',
        'div.ad-overlay',
        'div.ad-modal',
        'div.ad-notice',
        'div.ad-panel',
        'div.ad-sponsor',
        'div.ad-text',
        'div.ad-link',
        'div.ad-image',
        'div.ad-video',
        'div.ad-content',
        'div.ad-header',
        'div.ad-footer',
        'div.ad-sidebar',
        'div.ad-top',
        'div.ad-bottom',
        'div.ad-left',
        'div.ad-right',
        'div.ad-center',
        'div.ad-middle',
        'div.ad-full',
        'div.ad-half',
        'div.ad-quarter',
        'div.ad-third',
        'div.ad-two-thirds',
        'div.ad-three-quarters',
        'div.ad-one-third',
        'div.ad-two-thirds',
        'div.ad-one-quarter',
        'div.ad-three-quarters',
        'div.ad-one-half',
        'div.ad-one-fifth',
        'div.ad-two-fifths',
        'div.ad-three-fifths',
        'div.ad-four-fifths',
        'div.ad-one-sixth',
        'div.ad-two-sixths',
        'div.ad-three-sixths',
        'div.ad-four-sixths',
        'div.ad-five-sixths',
        'div.ad-one-seventh',
        'div.ad-two-sevenths',
        'div.ad-three-sevenths',
        'div.ad-four-sevenths',
        'div.ad-five-sevenths',
        'div.ad-six-sevenths',
        'div.ad-one-eighth',
        'div.ad-two-eighths',
        'div.ad-three-eighths',
        'div.ad-four-eighths',
        'div.ad-five-eighths',
        'div.ad-six-eighths',
        'div.ad-seven-eighths',
        'div.ad-one-ninth',
        'div.ad-two-ninths',
        'div.ad-three-ninths',
        'div.ad-four-ninths',
        'div.ad-five-ninths',
        'div.ad-six-ninths',
        'div.ad-seven-ninths',
        'div.ad-eight-ninths',
        'div.ad-one-tenth',
        'div.ad-two-tenths',
        'div.ad-three-tenths',
        'div.ad-four-tenths',
        'div.ad-five-tenths',
        'div.ad-six-tenths',
        'div.ad-seven-tenths',
        'div.ad-eight-tenths',
        'div.ad-nine-tenths',
    ];

    // Remove ads from the DOM
    adSelectors.forEach(selector => {
        document.querySelectorAll(selector).forEach(ad => {
            ad.remove();
        });
    });

    console.log('Universal Ad-Blocker enabled.');
})();
